[project]
name = "22-travel-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gaurav Singh", email = "grv08singh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
22-travel-agent = "22_travel_agent:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
